# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  projectName: demo
  appName: push
  localSettingsName: sample-local-settings  #Name of the Azure Key Vault key
  localSettingsFile: local_settings.json    #Filename when downloaded and mounted
  repository: '$(projectName)/$(appName)/$(Build.SourceBranchName)'
  artifactName: yaml-k8s

stages:
- stage: Build
  displayName: Build image and push to registry
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: buildAndPush
        containerRegistry: registryrjrdev
        repository: '$(repository)'
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
          latest
        addPipelineData: false
